/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stdint.h>
#include "app.h"



int main(void)
{
	APP_u8AppInit();

	APP_u8InitializeMotorPins();

	APP_u8CreateFilter();

    /* Loop forever */
	while(1)
	{

		APP_u8ReceiveDataFromCANBus();

		APP_u8DirectionDecision();

	}
}


u8 APP_u8AppInit(){
	RCC_voidClockInit();

	MTIM_voidInit();

	RCC_voidPeripheralClockEnable(RCC_APB2, IOPA);

	/* Enable TIMER2 clock */
	RCC_voidPeripheralClockEnable(RCC_APB1,TIM2);

	CAN_voidInit();
}

u8 APP_u8InitializeMotorPins(){
	/* PWM Motor pins */
	GPIO_voidSetPinMode(PORTA, PIN0, GPIO_AF_OUTPUT_PP_10MHZ);
	GPIO_voidSetPinMode(PORTA, PIN1, GPIO_AF_OUTPUT_PP_10MHZ);
	GPIO_voidSetPinMode(PORTA, PIN2, GPIO_AF_OUTPUT_PP_10MHZ);
	GPIO_voidSetPinMode(PORTA, PIN3, GPIO_AF_OUTPUT_PP_10MHZ);

	/* Motor enable pins */
	GPIO_voidSetPinMode(PORTA, PIN5, GPIO_GP_OUTPUT_PP_2MHZ);
	GPIO_voidSetPinMode(PORTA, PIN6, GPIO_GP_OUTPUT_PP_2MHZ);
	GPIO_voidSetPinMode(PORTA, PIN7, GPIO_GP_OUTPUT_PP_2MHZ);
	GPIO_voidSetPinMode(PORTA, PIN8, GPIO_GP_OUTPUT_PP_2MHZ);

	/* Enable Motor driver pins */
	GPIO_voidSetPinValue(PORTA, PIN5, GPIO_HIGH);
	GPIO_voidSetPinValue(PORTA, PIN6, GPIO_HIGH);
	GPIO_voidSetPinValue(PORTA, PIN7, GPIO_HIGH);
	GPIO_voidSetPinValue(PORTA, PIN8, GPIO_HIGH);
}

u8 APP_u8ReceiveDataFromCANBus(){
	CAN_voidReceive(&can_rx, 0, Directions_Received);
}

u8 APP_u8CreateFilter(){
	can_filter.FilterActivation = CAN_FILTER_ACTIVE;
	can_filter.FilterBank = CAN_FILTER_BANK_1;
	can_filter.FilterScale = CAN_FILTER_SCALE_SINGLE_32BIT;
	can_filter.FilterMode = CAN_FILTER_MODE_MASK;
	can_filter.FilterFIFOAssign = CAN_FILTER_FIFO_ASSIGN_0;
	can_filter.FilterIDHigh = 0;
	can_filter.FilterIDLow = 0 ;
	can_filter.FilterMaskIDHigh = 0 ;
	can_filter.FilterMaskIDLow = 0 ;

	CAN_voidConfigFilter(&can_filter);
}

u8 APP_u8DirectionDecision(){
	/* Stop case */
	if(Directions_Received[4] == 1)
	{
		Motor_u8Stop();
	}

	/* Forward case */
	else if(Directions_Received[0] == 1)
	{
		 Motor_u8MoveForward();
	}

	/* Backward case */
	else if(Directions_Received[1] == 1)
	{
		Motor_u8MoveBackward();
	}

	/* Right case */
	else if(Directions_Received[2] == 1)
	{
		Motor_u8TurnRight();
	}

	/* Left case */
	else if(Directions_Received[3] == 1)
	{
		Motor_u8TurnLeft();
	}

}
